<?php

/**
 * BaseSiteTransUnit
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $msg_id
 * @property integer $site_id
 * @property integer $cat_id
 * @property string $source
 * @property string $target
 * @property Site $Site
 * @property Catalogue $Catalogue
 * 
 * @method integer       getMsgId()     Returns the current record's "msg_id" value
 * @method integer       getSiteId()    Returns the current record's "site_id" value
 * @method integer       getCatId()     Returns the current record's "cat_id" value
 * @method string        getSource()    Returns the current record's "source" value
 * @method string        getTarget()    Returns the current record's "target" value
 * @method Site          getSite()      Returns the current record's "Site" value
 * @method Catalogue     getCatalogue() Returns the current record's "Catalogue" value
 * @method SiteTransUnit setMsgId()     Sets the current record's "msg_id" value
 * @method SiteTransUnit setSiteId()    Sets the current record's "site_id" value
 * @method SiteTransUnit setCatId()     Sets the current record's "cat_id" value
 * @method SiteTransUnit setSource()    Sets the current record's "source" value
 * @method SiteTransUnit setTarget()    Sets the current record's "target" value
 * @method SiteTransUnit setSite()      Sets the current record's "Site" value
 * @method SiteTransUnit setCatalogue() Sets the current record's "Catalogue" value
 * 
 * @package    s14cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSiteTransUnit extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('site_trans_unit');
        $this->hasColumn('msg_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('site_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('cat_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('source', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('target', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Site', array(
             'local' => 'site_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Catalogue', array(
             'local' => 'cat_id',
             'foreign' => 'cat_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}