<?php

/**
 * BaseBanner
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $site_id
 * @property integer $display_type
 * @property string $url
 * @property string $url_predefined
 * @property string $filename
 * @property string $html_alt
 * @property string $html_title
 * @property string $title
 * @property string $head_title
 * @property string $head_text
 * @property string $head_icon
 * @property clob $description
 * @property clob $content
 * @property integer $template
 * @property clob $custom_code
 * @property boolean $is_target_blank
 * @property boolean $is_active
 * @property boolean $show_title
 * @property Site $Site
 * 
 * @method integer getSiteId()          Returns the current record's "site_id" value
 * @method integer getDisplayType()     Returns the current record's "display_type" value
 * @method string  getUrl()             Returns the current record's "url" value
 * @method string  getUrlPredefined()   Returns the current record's "url_predefined" value
 * @method string  getFilename()        Returns the current record's "filename" value
 * @method string  getHtmlAlt()         Returns the current record's "html_alt" value
 * @method string  getHtmlTitle()       Returns the current record's "html_title" value
 * @method string  getTitle()           Returns the current record's "title" value
 * @method string  getHeadTitle()       Returns the current record's "head_title" value
 * @method string  getHeadText()        Returns the current record's "head_text" value
 * @method string  getHeadIcon()        Returns the current record's "head_icon" value
 * @method clob    getDescription()     Returns the current record's "description" value
 * @method clob    getContent()         Returns the current record's "content" value
 * @method integer getTemplate()        Returns the current record's "template" value
 * @method clob    getCustomCode()      Returns the current record's "custom_code" value
 * @method boolean getIsTargetBlank()   Returns the current record's "is_target_blank" value
 * @method boolean getIsActive()        Returns the current record's "is_active" value
 * @method boolean getShowTitle()       Returns the current record's "show_title" value
 * @method Site    getSite()            Returns the current record's "Site" value
 * @method Banner  setSiteId()          Sets the current record's "site_id" value
 * @method Banner  setDisplayType()     Sets the current record's "display_type" value
 * @method Banner  setUrl()             Sets the current record's "url" value
 * @method Banner  setUrlPredefined()   Sets the current record's "url_predefined" value
 * @method Banner  setFilename()        Sets the current record's "filename" value
 * @method Banner  setHtmlAlt()         Sets the current record's "html_alt" value
 * @method Banner  setHtmlTitle()       Sets the current record's "html_title" value
 * @method Banner  setTitle()           Sets the current record's "title" value
 * @method Banner  setHeadTitle()       Sets the current record's "head_title" value
 * @method Banner  setHeadText()        Sets the current record's "head_text" value
 * @method Banner  setHeadIcon()        Sets the current record's "head_icon" value
 * @method Banner  setDescription()     Sets the current record's "description" value
 * @method Banner  setContent()         Sets the current record's "content" value
 * @method Banner  setTemplate()        Sets the current record's "template" value
 * @method Banner  setCustomCode()      Sets the current record's "custom_code" value
 * @method Banner  setIsTargetBlank()   Sets the current record's "is_target_blank" value
 * @method Banner  setIsActive()        Sets the current record's "is_active" value
 * @method Banner  setShowTitle()       Sets the current record's "show_title" value
 * @method Banner  setSite()            Sets the current record's "Site" value
 * 
 * @package    s14cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBanner extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('banner');
        $this->hasColumn('site_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('display_type', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 2,
             ));
        $this->hasColumn('url', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('url_predefined', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('filename', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('html_alt', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('html_title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('head_title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('head_text', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('head_icon', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('content', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('template', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('custom_code', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('is_target_blank', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));
        $this->hasColumn('show_title', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Site', array(
             'local' => 'site_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sortable0 = new Doctrine_Template_Sortable(array(
             'uniqueBy' => 
             array(
              0 => 'site_id',
              1 => 'display_type',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($sortable0);
    }
}