<?php

/**
 * BaseContact
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $site_id
 * @property string $mail
 * @property string $name
 * @property string $phone
 * @property clob $message
 * @property clob $attachment
 * @property string $ip_address
 * @property string $sent_from
 * @property array $client_info
 * @property Site $Site
 * 
 * @method integer getSiteId()      Returns the current record's "site_id" value
 * @method string  getMail()        Returns the current record's "mail" value
 * @method string  getName()        Returns the current record's "name" value
 * @method string  getPhone()       Returns the current record's "phone" value
 * @method clob    getMessage()     Returns the current record's "message" value
 * @method clob    getAttachment()  Returns the current record's "attachment" value
 * @method string  getIpAddress()   Returns the current record's "ip_address" value
 * @method string  getSentFrom()    Returns the current record's "sent_from" value
 * @method array   getClientInfo()  Returns the current record's "client_info" value
 * @method Site    getSite()        Returns the current record's "Site" value
 * @method Contact setSiteId()      Sets the current record's "site_id" value
 * @method Contact setMail()        Sets the current record's "mail" value
 * @method Contact setName()        Sets the current record's "name" value
 * @method Contact setPhone()       Sets the current record's "phone" value
 * @method Contact setMessage()     Sets the current record's "message" value
 * @method Contact setAttachment()  Sets the current record's "attachment" value
 * @method Contact setIpAddress()   Sets the current record's "ip_address" value
 * @method Contact setSentFrom()    Sets the current record's "sent_from" value
 * @method Contact setClientInfo()  Sets the current record's "client_info" value
 * @method Contact setSite()        Sets the current record's "Site" value
 * 
 * @package    s14cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContact extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contact');
        $this->hasColumn('site_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('mail', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('phone', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('message', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('attachment', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('ip_address', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('sent_from', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('client_info', 'array', 1000, array(
             'type' => 'array',
             'notnull' => true,
             'length' => 1000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Site', array(
             'local' => 'site_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}