<?php

/**
 * BaseOptionKey
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $class_type
 * @property string $type
 * @property string $name
 * @property string $label
 * @property integer $k_group
 * @property boolean $is_required
 * @property string $variable_type
 * @property Doctrine_Collection $SiteSettings
 * 
 * @method string              getClassType()     Returns the current record's "class_type" value
 * @method string              getType()          Returns the current record's "type" value
 * @method string              getName()          Returns the current record's "name" value
 * @method string              getLabel()         Returns the current record's "label" value
 * @method integer             getKGroup()        Returns the current record's "k_group" value
 * @method boolean             getIsRequired()    Returns the current record's "is_required" value
 * @method string              getVariableType()  Returns the current record's "variable_type" value
 * @method Doctrine_Collection getSiteSettings()  Returns the current record's "SiteSettings" collection
 * @method OptionKey           setClassType()     Sets the current record's "class_type" value
 * @method OptionKey           setType()          Sets the current record's "type" value
 * @method OptionKey           setName()          Sets the current record's "name" value
 * @method OptionKey           setLabel()         Sets the current record's "label" value
 * @method OptionKey           setKGroup()        Sets the current record's "k_group" value
 * @method OptionKey           setIsRequired()    Sets the current record's "is_required" value
 * @method OptionKey           setVariableType()  Sets the current record's "variable_type" value
 * @method OptionKey           setSiteSettings()  Sets the current record's "SiteSettings" collection
 * 
 * @package    s14cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOptionKey extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('option_key');
        $this->hasColumn('class_type', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('type', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('label', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('k_group', 'integer', 2, array(
             'type' => 'integer',
             'length' => 2,
             ));
        $this->hasColumn('is_required', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));
        $this->hasColumn('variable_type', 'string', 63, array(
             'type' => 'string',
             'length' => 63,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('SiteSetting as SiteSettings', array(
             'local' => 'id',
             'foreign' => 'option_key_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}