<?php

/**
 * BaseSiteSetting
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $site_id
 * @property integer $option_key_id
 * @property clob $s_value
 * @property string $lang
 * @property boolean $is_active
 * @property integer $priority
 * @property boolean $is_read_only
 * @property Site $Site
 * @property OptionKey $OptionKey
 * 
 * @method integer     getSiteId()        Returns the current record's "site_id" value
 * @method integer     getOptionKeyId()   Returns the current record's "option_key_id" value
 * @method clob        getSValue()        Returns the current record's "s_value" value
 * @method string      getLang()          Returns the current record's "lang" value
 * @method boolean     getIsActive()      Returns the current record's "is_active" value
 * @method integer     getPriority()      Returns the current record's "priority" value
 * @method boolean     getIsReadOnly()    Returns the current record's "is_read_only" value
 * @method Site        getSite()          Returns the current record's "Site" value
 * @method OptionKey   getOptionKey()     Returns the current record's "OptionKey" value
 * @method SiteSetting setSiteId()        Sets the current record's "site_id" value
 * @method SiteSetting setOptionKeyId()   Sets the current record's "option_key_id" value
 * @method SiteSetting setSValue()        Sets the current record's "s_value" value
 * @method SiteSetting setLang()          Sets the current record's "lang" value
 * @method SiteSetting setIsActive()      Sets the current record's "is_active" value
 * @method SiteSetting setPriority()      Sets the current record's "priority" value
 * @method SiteSetting setIsReadOnly()    Sets the current record's "is_read_only" value
 * @method SiteSetting setSite()          Sets the current record's "Site" value
 * @method SiteSetting setOptionKey()     Sets the current record's "OptionKey" value
 * 
 * @package    s14cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSiteSetting extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('site_setting');
        $this->hasColumn('site_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('option_key_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('s_value', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('lang', 'string', 2, array(
             'type' => 'string',
             'length' => 2,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('priority', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 1,
             ));
        $this->hasColumn('is_read_only', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Site', array(
             'local' => 'site_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('OptionKey', array(
             'local' => 'option_key_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}