generator:
  class: sfDoctrineGenerator
  param:
    model_class:           TeamMember
    theme:                 custom_theme
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          team_member
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
         display: [id, _site_id, _img, title, is_active, position, updated_at]
         table_method: retrieveBackendEntityList
         object_actions:
           _edit:        ~
      filter:
        class: false
      form:
        class: BackendTeamMemberForm
        actions:
          _save: ~
          _save_and_add: ~
          _list: ~
          _delete: ~
      edit:    ~
      new:     ~
