<?php

/**
 * Banner
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    s14cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Banner extends BaseBanner
{

    public function getFinalHtmlCaptionId(){
        return "nslidercaption_os_".$this->id;
    }

    public function getFinalHtmlAlt(){
        return $this->getHtmlAlt();
    }

    public function getFinalContent($esc_type = "esc_raw"){
        return $this->getContent($esc_type);
    }

    /**
     * Returns the Image url for a Banner object.
     *
     * @param string $image_field The field name where image src is stored.
     * @param string $sf_culture Culture code.
     *
     * @return null|string The image url or null if it's not exists.
     */
    public function getImageLink($image_field = "filename", $sf_culture = null) {
        $asset_image_type = "";

        if ($image_field == "filename") {
            $asset_image_type = "banner_image";
        }

        $final_image = null;
        $final_image = $this->filename;
        /*
        $translation = isset($this->Translation[$sf_culture]) ? $this->Translation[$sf_culture] : $this->Translation["en"];


        if ($translation && isset($translation[$image_field])) {
            $final_image = $translation[$image_field];
        }
        */

        if ($final_image) {
            return AssetImageHelper::getFullUrl($asset_image_type, $final_image);
        }

        return null;
    }//end getImageLink()

    public function getFinalUrl(){

        $ret_val = "#";
        if($this->getUrl()){
            $ret_val = $this->getUrl();
        }
        if($this->getUrlPredefined()){
            $ret_val = SeoUrlHelper::unescapeUrlPredefinedChoice($this->getUrlPredefined());
        }

        return $ret_val;

    }


}
