<?php

/**
 * CatalogueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CatalogueTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return CatalogueTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Catalogue');
    }
}