<?php

/**
 * Cms
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    s14cms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Cms extends BaseCms
{
    use TraitMainDisplay;

    public static $final_seo_params_show_suffix = "cms_show";

    //use TraitFrontendGeneralSeoFields;

    public function getFinalTitle(){

        return $this->getTitle();

    }

    /**
     * Returns the seoable strings array by adding object meta data fallback.
     *
     * @return array
     */
    public function getFinalObjectSeoParams() {
        return $this->getFinalSeoParams(true);
    }//end getFinalObjectSeoParams()

    /**
     * Returns the translateable seo strings for an Article.
     *
     * @param bool $with_object_values If use fallback with object meta values or not.
     *
     * @return array Array of strings. Each string a seoable element on the page.
     */
    public function getFinalSeoParams($with_object_values = false) {
        $prefix = Translate::glue(array(GeneralSeoHelper::getTranslatePrefix(), "cms_show"));

        $args = array(
            "%1%" => $this->getTitle()
        );

        if ($with_object_values) {
            $values = $this->getSeoTagArray();

            return GeneralSeoHelper::getTranslated($prefix, $args, $values);
        }

        return GeneralSeoHelper::getTranslated($prefix, $args, null);
    }//end getFinalSeoParams()

    public function getFinalContent($esc_type = 'esc_raw'){

        return $this->getContent($esc_type);

    }

    public function getFinalObjectSlug($sf_culture = null){

        return $this->getSlug();

    }
}
