<?php

/**
 * ContactTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContactTable extends Doctrine_Table
{
    use TraitBaseTableMethods;
    /**
     * Returns an instance of this class.
     *
     * @return ContactTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Contact');
    }
}