<?php

/**
 * QuoteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class QuoteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return QuoteTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Quote');
    }
}