<?php

/**
 * SiteMenuTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SiteMenuTable extends Doctrine_Table
{

    use TraitBaseTableMethods;

    public static function addMenuTreeQueryBySite($site_id = null) {

        $query = self::getInstance()
            ->createQuery('sm')
            ->leftJoin('sm.ChildMenus cm')
            ->andWhere('sm.site_id = ?', $site_id);

        return $query;
    }

    public static function getSiteMenuTreeByRootId($site_id = null, $root_id = null) {
        if(is_null($root_id) || is_null($site_id)){
            return null;
        }

        $query = self::addMenuTreeQueryBySite($site_id);
        $query->andWhere('sm.parent_id = ?', $root_id)
            ->addOrderBy('sm.parent_id')
            ->addOrderBy('sm.position');
        $result = $query->execute();

        return $result;

    }//end getSiteMenuTreeByRootId()

    /**
     * Returns an instance of this class.
     *
     * @return SiteMenuTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SiteMenu');
    }

    public static function retrieveBackendEntityList(){
        $q = self::getAllEntitiesQuery();
        $q
            ->addOrderBy("site_id asc")
            ->addOrderBy("parent_id asc")
            ->addOrderBy("position asc")
        ;
        return $q;
    }
}