<?php

/**
 * SiteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SiteTable extends Doctrine_Table
{

    use TraitBaseTableMethods;

    public static function findByDomain($domain_name_full)
    {
        $all_sites = self::getActiveEntitiesAsArray();
        $sites_array = array();

        foreach($all_sites as $one_site) {
            $site_array = [];
            $site_array[] = $one_site['domain'];
            if ($one_site['domain_dev']) {
                $site_array[] = $one_site['domain_dev'];
            }

            $one_site_domain_aliases = explode(",", preg_replace('/\s+/', '', $one_site['domain_alias']));
            foreach($one_site_domain_aliases as $osda) {
                if (strlen($osda) > 3) {
                    $site_array[] = $osda;
                }
            }

            $one_site_domain_dev_aliases = explode(",", preg_replace('/\s+/', '', $one_site['domain_dev_alias']));
            foreach($one_site_domain_dev_aliases as $osda) {
                if (strlen($osda) > 3) {
                    $site_array[] = $osda;
                }
            }

            $sites_array[$one_site['id']] = $site_array;

            if(in_array($domain_name_full, $sites_array[$one_site['id']])){

                $current_site_object = SiteTable::getActiveEntityById($one_site['id']);
                return $current_site_object;

            }

        }

        return null;
    }

    /**
     * Returns an instance of this class.
     *
     * @return SiteTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Site');
    }
}