<?php

/**
 * TeamMemberTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TeamMemberTable extends Doctrine_Table
{

    use TraitBaseTableMethods;
    use TraitBaseTableBySiteMethods;

    /**
     * Returns an instance of this class.
     *
     * @return TeamMemberTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TeamMember');
    }
}