<?php

/**
 * TransUnitTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TransUnitTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return TransUnitTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TransUnit');
    }
}