default:
  http_metas:
    content-type: text/html

  metas:
    #title:        "ProjectName | projectdomain "
    #description:  ""
    #keywords:     ""
    #language:     en
    #robots:       noindex, nofollow

  stylesheets:
    - /resources_core/bootstrap_core/css/bootstrap.min.css
    - /resources_core/bootstrap_core/css/bootstrap-theme.min.css
    - /resources_core/plugins/fontawesome/css/font-awesome.min.css

    - /resources_core/plugins/prettyPhoto/css/prettyPhoto.css
    - /resources_core/plugins/supslides/stylesheets/superslides.css

    - /resources/css/fonts.css
    - /resources/css/ccnt.css
    - /resources/css/layout.css

  javascripts:
    - /resources_core/jquery/jquery-1.11.3.min.js
    - /resources_core/bootstrap_core/js/bootstrap.min.js

    - /resources_core/plugins/prettyPhoto/js/jquery.prettyPhoto.js
    - /resources_core/plugins/supslides/jquery.superslides.js
    - /resources/js/site.js

  has_layout:     true
  layout:         layout
