<?php

/**
 * sfCombineTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfCombineTable extends PluginsfCombineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return sfCombineTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfCombine');
    }
}