#||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
# T R A N S L A T E
#||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
TransUnit:
  columns:
    msg_id:                 { type: integer, primary: true, autoincrement: true }
    cat_id:                 { type: integer, default: 1 }
    source:                 { type: string }
    target:                 { type: string }
    comments:               { type: string(255) }
    date_added:             { type: integer, default: 0 }
    date_modified:          { type: integer, default: 0 }
    author:                 { type: string(255) }
    translated:             { type: integer(1) }
  relations:
    Catalogue:
      local:                cat_id
      foreign:              cat_id
      foreignAlias:         Catalogue
      type:                 one

Catalogue:
  columns:
    cat_id:                 { type: integer, primary: true, autoincrement: true }
    name:                   { type: string(100) }
    source_lang:            { type: string(100) }
    target_lang:            { type: string(100) }
    date_created:           { type: integer }
    date_modified:          { type: integer }
    author:                 { type: string(255) }
  relations:
    TransUnit:
      local:                cat_id
      foreign:              cat_id
      foreignAlias:         Catalogue
      type:                 many

# SiteTransUnit::
SiteTransUnit:
  columns:
    msg_id:                                 { type: integer, primary: true, autoincrement: true }
    site_id:                                { type: integer, notnull: true }
    cat_id:                                 { type: integer, notnull: true }
    source:                                 { type: string }
    target:                                 { type: string }
  relations:
    Site:
      onDelete:                             CASCADE
      foreignAlias:                         SiteTransUnits
    Catalogue:
      local:                                cat_id
      foreign:                              cat_id
      foreignAlias:                         SiteTransUnits
      type:                                 one
  actAs:
    Timestampable:                          ~
